#!/bin/bash
echo "Installing RasPad Launcher..."

echo "Download qt runtime"
wget https://github.com/raspad-tablet/qt5pi/releases/download/v1.0/qt5pi.zip
unzip qt5pi.zip
cp -r ./qt5pi /usr/local/qt5pi

echo "Copy raspad launcher"
cp ./applications/raspad-faq.desktop /usr/share/applications/
cp ./applications/raspad-launcher.desktop /usr/share/applications/

cp ./icons/raspad.png /usr/share/icons/

cp ./bin/raspad-launcher /usr/local/bin/
cp ./bin/raspad-launcher-helper /usr/local/bin/

chmod +x /usr/local/bin/raspad-launcher
chmod +x /usr/local/bin/raspad-launcher-helper

echo "Install matchbox-keyboard"
apt install matchbox-keyboard

echo "Install screen auto rotator"
git clone --depth=1 https://github.com/sunfounder/python-sh3001
cd python-sh3001
python3 install.py
cd ..
