#!/bin/bash
echo "Uninstalling RasPad Launcher..."

echo "Remove qt runtime"
# cp -r ./qt5pi /usr/local/qt5pi
rm -rf /usr/local/qt5pi

echo "Remove raspad launcher"
rm -rf /usr/share/applications/raspad-faq.desktop
rm -rf /usr/share/applications/raspad-launcher.desktop

rm -rf /usr/share/icons/raspad.png

rm -rf /usr/local/bin/raspad-launcher
rm -rf /usr/local/bin/raspad-launcher-helper

if test -f "/home/pi/.config/lxpanel/LXDE-pi/panels/panel.bak"; then
    mv /home/pi/.config/lxpanel/LXDE-pi/panels/panel.bak /home/pi/.config/lxpanel/LXDE-pi/panels/panel
else
    rm -r /home/pi/.config/lxpanel/LXDE-pi/panels/panel
fi

echo "Uninstall matchbox-keyboard"
apt install matchbox-keyboard

echo "Uninstall screen auto rotator"
pip3 uninstall sh3001
rm -rf /usr/bin/rotate-helper
rm -rf /home/pi/.config/auto-rotator
